version: '3'

services:
  ipt:
    image: gbif/ipt
    expose:
      - '80:8080'
    volumes:
      - ./data-directory:/srv/ipt
    environment:
      - VIRTUAL_HOST=archive.gbif.no

networks:
  default:
    external:
      name: nginx-proxy
