version: '3'

services:
  ipt:
    image: gbif/ipt:2.4.0
    expose:
      - '8080'
    volumes:
      - ./data-directory:/srv/ipt
    environment:
      - VIRTUAL_HOST=ipt-test.gbif.no
      - LETSENCRYPT_HOST=ipt-test.gbif.no

networks:
  default:
    external:
      name: nginx-proxy
